import { MenuItem, Review } from './types';

export const INITIAL_MENU: MenuItem[] = [
  {
    id: '1',
    name: 'Margherita Supreme',
    description: 'Classic tomato sauce, fresh mozzarella, basil, and extra virgin olive oil.',
    price: 399,
    category: 'Pizza',
    image: 'https://picsum.photos/seed/pizza1/400/300',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Pepperoni Feast',
    description: 'Double pepperoni, mozzarella cheese, and our signature tomato sauce.',
    price: 499,
    category: 'Pizza',
    image: 'https://picsum.photos/seed/pizza2/400/300',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Veggie Delight',
    description: 'Bell peppers, onions, mushrooms, olives, and fresh tomatoes.',
    price: 449,
    category: 'Pizza',
    image: 'https://picsum.photos/seed/pizza3/400/300',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isPopular: false,
    isAvailable: true,
  },
  {
    id: '4',
    name: 'BBQ Chicken',
    description: 'Grilled chicken, BBQ sauce, red onions, and cilantro.',
    price: 549,
    category: 'Pizza',
    image: 'https://picsum.photos/seed/pizza4/400/300',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Garlic Breadsticks',
    description: 'Warm, buttery breadsticks topped with garlic and parmesan.',
    price: 149,
    category: 'Sides',
    image: 'https://picsum.photos/seed/bread/400/300',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isPopular: false,
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce, croutons, parmesan, and creamy caesar dressing.',
    price: 249,
    category: 'Starters',
    image: 'https://picsum.photos/seed/salad/400/300',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isPopular: false,
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Chocolate Lava Cake',
    description: 'Rich chocolate cake with a molten center, served with vanilla ice cream.',
    price: 199,
    category: 'Desserts',
    image: 'https://picsum.photos/seed/cake/400/300',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isPopular: true,
    isAvailable: true,
  },
  {
    id: '8',
    name: 'Craft Cola',
    description: 'Artisanal cola made with real cane sugar.',
    price: 99,
    category: 'Beverages',
    image: 'https://picsum.photos/seed/cola/400/300',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isPopular: false,
    isAvailable: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: '1',
    author: 'Sarah Jenkins',
    rating: 5,
    text: 'The best pizza I have had in years! The crust was perfect.',
    date: '2023-10-15',
  },
  {
    id: '2',
    author: 'Mike Ross',
    rating: 4,
    text: 'Great atmosphere and friendly staff. Pizza was delicious.',
    date: '2023-10-12',
  },
  {
    id: '3',
    author: 'Emily Blunt',
    rating: 5,
    text: 'Loved the vegan options. Finally a good vegan cheese!',
    date: '2023-10-10',
  },
];